version: "3.8"

services:
  frontend:
    build: .
    command: ["python","app1.py"]
    networks:
      - sample_network
    ports:
      - "5000:5000"
    container_name: app1
  backend:
    build: .
    command: ["python","app2.py"]
    networks:
      - sample_network
    ports:
      - "5001:5001"
    container_name: app2

networks:
  sample_network:
